[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = [
    "-h",
] }

[tasks.objcopy-central]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "central",
    "--",
    "-O",
    "ihex",
    "rmk-central.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-peripheral-right]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "peripheral-right",
    "--",
    "-O",
    "ihex",
    "rmk-peripheral-right.hex",
]
dependencies = ["install-llvm-tools"]

[tasks.objcopy-peripheral-left]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "peripheral-left",
    "--",
    "-O",
    "ihex",
    "rmk-peripheral-left.hex",
]
dependencies = ["install-llvm-tools"]

[tasks.uf2-central]
command = "python"
args = [
    "scripts/uf2conv.py",
    "rmk-central.hex",
    "-c",
    "-f",
    "NRF52840",         # TODO: Use your chip family ID in the uf2conv.py file as -f argument
    "-o",
    "rmk-central.uf2",
]
dependencies = ["objcopy-central"]

[tasks.uf2-peripheral-right]
command = "python"
args = [
    "scripts/uf2conv.py",
    "rmk-peripheral-right.hex",
    "-c",
    "-f",
    "NRF52840",         # TODO: Use your chip family ID in the uf2conv.py file as -f argument
    "-o",
    "rmk-peripheral-right.uf2",
]
dependencies = ["objcopy-peripheral-right"]

[tasks.uf2-peripheral-left]
command = "python"
args = [
    "scripts/uf2conv.py",
    "rmk-peripheral-right.hex",
    "-c",
    "-f",
    "NRF52840",         # TODO: Use your chip family ID in the uf2conv.py file as -f argument
    "-o",
    "rmk-peripheral-left.uf2",
]
dependencies = ["objcopy-peripheral-left"]

[tasks.uf2]
dependencies = ["uf2-central", "uf2-peripheral-right", "uf2-peripheral-left"]
